# Generated by Django 4.1.3 on 2022-11-14 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upracticeapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upresult',
            fields=[
                ('upresult_id', models.AutoField(primary_key=True, serialize=False)),
                ('upresult_accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upresult_speed', models.IntegerField()),
                ('udate_time', models.DateTimeField(auto_now_add=True)),
                ('upresult_time', models.IntegerField()),
                ('upresult_false_num', models.IntegerField()),
                ('upresult_summary', models.TextField()),
                ('upractice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upracticeapp.upractice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
